### ISSUE TITLE
open-sans-32-black.fnt font missing during rendering

### ISSUE THREAD

**Issue by sldblog** [FundingCircle/fc4-framework#147]
I'm trying the 34293b8 version of the framework tool and I'm getting the following error (linebreaks added by me):

```
RENDERING FAILED: Error: File '/**/root/project/tool/renderer/node_modules/@jimp ⏎
  /plugin-print/fonts/open-sans/open-sans-32-black/open-sans-32-black.fnt' ⏎
  was not included into executable at compilation stage. ⏎
  Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:650:29)
    at Object.fs.readFile (pkg/prelude/bootstrap.js:716:5)
    at loadFont (/snapshot/root/project/tool/renderer/node_modules/load-bmfont/index.js:51:8)
    at _default.constants.loadFont (/snapshot/root/project/tool/renderer/node_modules/@jimp/plugin-print/dist/index.js:170:35)
    at new Promise (<anonymous>)
    at Function.loadFont (/snapshot/root/project/tool/renderer/node_modules/@jimp/plugin-print/dist/index.js:165:16)
    at conjoin (/snapshot/root/project/tool/renderer/render.js:0:0)
```

It looks like the fonts are missing from the package. I have tried a few different releases and it seems the rendering was working fine in the previous release:

| Version | Full release name | Works |
| --- | --- | --- |
| pre-release 587351b | `fc4-tool-mac-amd64-587351b.tar.gz` |  🚫no, complains about `open-sans-32-black.fnt` |
| release 34293b8 | `fc4-tool-mac-amd64-34293b8.tar.gz` | 🚫no, complains about `open-sans-32-black.fnt` | 
| release cfafc45 | `fc4-tool-mac-amd64-cfafc45.tar.gz` | ✅ yes, renders fine |

**Comment by aviflax** [comment]
Thank you for the excellent bug report!

I’m going to figure out how to reproduce, add a test, and hopefully fix ASAP.

**Comment by aviflax** [comment]
Interesting:

I have [a test in the CI config](https://github.com/FundingCircle/fc4-framework/blob/46d53116f29104021d7854bfa12c1d66cdad2aaf/.circleci/config.yml#L60) that should have caught this, but it didn’t (see e.g. [this build](https://circleci.com/gh/FundingCircle/fc4-framework/1242#artifacts/containers/0)) because that test runs on Linux (Debian) — so it would seem that this is a MacOS-only bug.

I’m going to try to reproduce in the CI environment.

**Comment by aviflax** [comment]
I’ve figured out how to reproduce. It has nothing to do with Linux vs Mac; the test was bad. The test environment wasn’t sufficiently isolated from the package-building environment. I’ll open a PR tomorrow that reproduces and then fixes the bug.

**Comment by aviflax** [comment]
Sorry for the delay on the fix — been traveling. Coming real soon now!

**Comment by aviflax** [comment]
@sldblog I’ve opened #148 to fix this. Feel free to review, if you’re so inclined. Thanks!

**Comment by sldblog** [comment]
Happy to confirm that https://github.com/FundingCircle/fc4-framework/tree/release_2019-03-11_1354 works ✅ 

Thank you for the quick fix 🙇

**Comment by aviflax** [comment]
Wonderful, my pleasure!
