### ISSUE TITLE
Simplify the CLI

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#168]
In #153, @Ninju and I discussed some issues with the current design of the CLI, especially the different subcommands and what they mean.

Specifically:

* It’s very non-obvious what the `edit` and `process` subcommands do
* The `edit` and `process` subcommands both tightly couple the snapping of coords to a virtual grid, the reformatting of the diagram YAML, and rendering — which doesn’t seem necessary.
* It’d probably be better to just let users choose which of those features they want to be active, on the fly.
* If we use “short options” (e.g. `-r`) rather than subcommands, we could allow them to be grouped (or bundled) together, à la `tar`, e.g. `tar -xzv …`

In that discussion I proposed doing away with the subcommands:

> So perhaps `fc4` could have these switches:
>
> * `-f or --format` to format the YAML
> * `-s or --snap` to snap the coords to the grid
> * `-r or --render` to render the diagrams to PNG files
> * `-w or --watch` to stay persistent, watch the supplied paths for changes, and when changes are observed, apply the actions specified via some combination of `-f/s/r`
>
> In this scenario, `fc4 process <path...>` could be replaced by `fc4 -fsr <file>` and `fc4 edit <path...>` could be replaced by `fc4 -fsrw <path…>`. And of course someone could specify just one or two actions, whatever they want.

I’ve been rolling that over in the back of my head since then, and I feel good about that proposal. So let’s go ahead and do it!

Some notes:

* This will require some preparatory refactoring to decouple snapping from formatting… well worth doing anyway
* This will reduce duplication in the codebase
* This will reduce total LoC
* This will significantly reduce untested LoC

**Comment by aviflax** [comment]
I’ve been thinking that in order to ensure that the design of the CLI is clear, intuitive, and logical, I need to think about future switches/options we might add, so as to make sure we’re using the best set of options as a holistic set.

Some future options I suspect we might want to add, in addition to those specified above:

* `--debug` to activate debug mode
* `-v or --verbose or —verbosity` to toggle/specify verbose mode or maybe a verbosity level
* `-l or --lint` to check formatting
* `-m or --model` to specify the model to use (when the new DSL (#73) is fully implemented+supported)
* `-e or --export` to export FC4 views (as per #73) to Structurizr Express diagrams
* `-o or --output-format` to specify the output format used (png, svg, pdf, etc)
* `--recursive` to toggle whether directories should be searched recursively for diagrams/views

**Comment by aviflax** [comment]
Another possible future option: `-i or --initial` as a modifier to `-w or --watch` — normally, when starting in watch mode, the tool does _not_ process the specified paths immediately; rather, it watches for changes and processed the files that are detected as changed. With `-i` specified, the tool would do both.

**Comment by aviflax** [comment]
@sldblog I’m almost ready to introduce the new CLI switches as described above, and I’m trying to decide if I should retain the current “subcommands” (`edit`, `render`, etc) alongside the new switches (with a deprecation notice) so as to ease the transition — or whether to just cut over, given that the framework has very few users and maybe it’d be easy for them to adapt to the change. Any thoughts?

**Comment by sldblog** [comment]
Thanks for pinging me, @aviflax! The changes look great.

I support the cut-over, but with guidance in the `--help`. My approach with an existing command that stopped working would be to look at the command's help so if that guides me to the "new way" of usage that would be fine.

On a side note, I like git's approach: the subcommands it has are all accessible through a "common" interface, e.g. the `git-checkout` command is accessible through `git checkout`, so it may be possible to keep small bin scripts that effectively use the new "--flag" interface.

**Comment by aviflax** [comment]
@sldblog thanks for the feedback!

Based on your feedback, I’ve taken some time (in my current WIP branch) to have the tool output helpful messages when someone runs it with a legacy command.

For example:

```
$ fc4 edit my-diagram.yaml
The subcommand `edit` is no longer supported. Equivalent behavior can be invoked via:
  fc4 -fsrw PATH [PATH...]
For more information please run `fc4 --help` and/or see https://git.io/fjVkL
```

and:

```
$ fc4 render my-diagram.yaml
The subcommand `render` is no longer supported. Equivalent behavior can be invoked via:
  fc4 -r PATH [PATH...]
For more information please run `fc4 --help` and/or see https://git.io/fjVkL
```

And here’s the current output of `--help`:

```
$ fc4 --help
Usage: fc4 OPTIONS PATH [PATH...]

Options:
  -f, --format  Rewrites diagram YAML files, reformatting the YAML to improve readability and diffability.
  -s, --snap    Rewrites diagram YAML files, snapping elements to a grid and aligning elements.
  -r, --render  Creates PNG image files that contain the visualization of each diagram as specified in the YAML files.
  -w, --watch   Watches the diagrams in/under the specified paths and processes them (as per the options above) when they change.
  -h, --help    Prints the synopsis and a list of the most commonly used commands and exits. Other options are ignored.
      --debug   For use by developers working on fc4 (the tool).

Full documentation is at https://fundingcircle.github.io/fc4-framework/tool/
```

What do you think? Suggestions welcome!

**Comment by aviflax** [comment]
@sldblog just FYI, [last week’s release](https://github.com/FundingCircle/fc4-framework/releases/tag/release_2019-07-10_1868) includes the new CLI. Thanks for the help!
