### ISSUE TITLE
Performance tests time out locally

### ISSUE THREAD

**Issue by j-po** [FundingCircle/fc4-framework#186]
This is rough to specify because it depends on the developer's local machine, but across multiple local runs (using Docker), I've been unable to get the new fc4 tool performance tests to pass. Given that the recommended test method is CI (where I imagine they pass), this isn't the end of the world, but it's also not ideal.

To resolve this issue, I recommend expanding the allowed timeout period and/or making it easier to selectively run/exclude the performance tests in different test runs (e.g. using `circleci.test`-style test selectors)

**Comment by aviflax** [comment]
Closing this as stale, as I’m currently the only person running the tests locally (that I know of) and I haven’t seen this problem.

If you run into this problem, please re-open!
