### ISSUE TITLE
Add prompt for feedback to the home page of the website

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#210]
As suggested by @miketheman — thanks Mike!

**Comment by aviflax** [comment]
I added a prompt with #257 ([here](https://github.com/FundingCircle/fc4-framework/pull/257/files#diff-1a523bd9fa0dbf998008b37579210e12R74)) — which is viewable on the home page: [Help & Feedback](https://fundingcircle.github.io/fc4-framework/).

@miketheman do you think that’s sufficient? It’s a little curt, maybe; perhaps we should make it a little more solicitous.

**Comment by miketheman** [comment]
@aviflax I think this is likely sufficient - thanks!

**Comment by aviflax** [comment]
Great, thanks Mike!
