### ISSUE TITLE
diagram renders what appears to be a default png

### ISSUE THREAD

**Issue by miketheman** [FundingCircle/fc4-framework#223]
```
fundingcircle/floss/fc4: stable 2019.10.04-117ecb9
/usr/local/Cellar/fc4/2019.10.04-117ecb9 (5 files, 21.2MB) *
  Built from source on 2019-10-10 at 09:44:29
```

@ifyoumakeit brought up to me that the tool appears to have changed behavior and introduced some bug either here or in structurizer?

A previously-constructed workingSystem Landscape diagram now renders content that isn't correct:

![wp-system-landscape](https://user-images.githubusercontent.com/529516/67869586-042cda00-fb04-11e9-9119-0eed692bd51f.png)

Debug command output, in case this helps:

```shellsession
$ fc4 --debug -fsrw diagrams/
*DEBUG*
Parsed Command Line:
{:options
 {:debug true, :format true, :snap true, :render true, :watch true},
 :arguments ["diagrams/"],
 :summary
 "  -f, --format                 Rewrites diagram YAML files, reformatting the YAML to improve readability and diffability.\n  -s, --snap                   Rewrites diagram YAML files, snapping elements to a grid and aligning elements.\n  -r, --render                 Creates image files that contain the visualization of each diagram as specified in the YAML files. The format(s) can be specified via -o/--output-formats.\n  -o, --output-formats FORMAT  Specifies the output format(s) for rendering diagrams. Allowed only when -r/--render is specified. Value is a character-delimited list of output formats. Supported formats are 'png' and 'svg'; supported delimiters are '+' (plus sign) and ',' (comma). If not specified, the default is 'png'. NB: svg output is written to files with the extension '.html'.\n  -w, --watch                  Watches the diagrams in/under the specified paths and processes them (as per the options above) when they change.\n  -h, --help                   Prints the synopsis and a list of the most commonly used commands and exits. Other options are ignored.\n      --debug                  For use by developers working on fc4 (the tool).",
 :errors nil}
Creating renderer with options: {:structurizr-express-url https://structurizr.com/express, :timeout-ms 30000, :headless true, :debug-port 9222, :debug-conn-timeout-ms 5000, :output-formats #{:png}}
Starting browser with options: [/Applications/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=9222 --headless --incognito]
📣 Now watching for changes to YAML files under specified paths...
wp-system-landscape.yaml
   in active set:   false
   in recent set:   false
   last-processed:
   current time:    10:57:44.216
   since-processed: nil
   process?:        true
10:57:44 wp-system-landscape.yaml modified; reading+parsing+validating...✅ formatting...✅ snapping...✅calling render-diagram-file for #object[java.io.File 0x555321d6 /Users/miketheman/architecture/diagrams/wp-system-landscape.yaml] with options {:debug true, :format true, :snap true, :render true, :watch true}
 rendering...Rendering with options: {:headless true, :format true, :snap true, :debug true, :debug-port 9222, :render true, :debug-conn-timeout-ms 5000, :output-formats #{:png}, :watch true, :structurizr-express-url https://structurizr.com/express, :timeout-ms 30000}
Loading Structurizr Express from https://structurizr.com/express
wp-system-landscape.yaml
   in active set:   true
   in recent set:   true
   last-processed:  10:57:44.220
   current time:    10:57:45.212
   since-processed: 992
   process?:        false
Setting YAML and updating diagram...
Extracting diagram as PNG...
Conjoining diagram and key...
result of rendering: {:fc4.rendering/images {:fc4.rendering/png {:fc4.rendering.png/main #object[[B 0x69e6d59e [B@69e6d59e], :fc4.rendering.png/key #object[[B 0x5adbed69 [B@5adbed69], :fc4.rendering.png/conjoined #object[[B 0x2800dc89 [B@2800dc89]}}}
checking result for errors...
checking image data size...
rendering seems to have succeeded!
processing format :fc4.rendering/png with value {:fc4.rendering.png/main #object[[B 0x69e6d59e [B@69e6d59e], :fc4.rendering.png/key #object[[B 0x5adbed69 [B@5adbed69], :fc4.rendering.png/conjoined #object[[B 0x2800dc89 [B@2800dc89]}
writing conjoined diagram found in :fc4.rendering.png/conjoined to /Users/miketheman/architecture/diagrams/wp-system-landscape.png
✅
wp-system-landscape.png
   in active set:   false
   in recent set:   false
   last-processed:
   current time:    10:57:50.326
   since-processed: nil
   process?:        false
```

**Comment by aviflax** [comment]
@miketheman and/or @ifyoumakeit I’m having trouble reproducing, so a few questions:

* which OS and version?
* which JRE?
* which browser: Chrome or Chromium? version?
* basic hardware specs? (CPU, RAM, disk)
* network quality — just a rough impression; were you using a known network and does that network tend to be fast/slow/reliable?

Thank you!

**Comment by aviflax** [comment]
Also:

* Size of the diagram YAML and PNG in KB?

**Comment by miketheman** [comment]
@aviflax thanks for trying to repro, here's some details:

- which OS and version? macOS Mojave 10.14.6 (18G103)
- which JRE?  Java(TM) SE Runtime Environment (build 1.8.0_172-b11) ; Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
-  which browser: Chrome or Chromium? version? I have both Chrome and Chromium - updated Chromium to 80.0.3950.0 - previously seen on 75.x as well.
- basic hardware specs? (CPU, RAM, disk) 3.1GHz Core i5, 16GB RAM, 250GB SSD, plenty of room
- network quality — just a rough impression; were you using a known network and does that network tend to be fast/slow/reliable? - office fiber network - pretty reliable.

- yaml size: 4743 bytes
- png size: used to be 843450, the example rendered is 71913

**Comment by aviflax** [comment]
Thanks Mike, that’s all very helpful. That OS and hardware are quite similar to the laptop I’m using, so I’ll try to reproduce with the same JRE and browser. If that doesn’t work I’ll be out of ideas… but maybe I’ll try coming up with a debug build that @ifyoumakeit could run, that might have some code to attempt to detect this particular failure case and abort.

**Comment by ifyoumakeit** [comment]
Hi! Thanks for looking into this! I looked into this and it looks like it was a combination of two issues, the second being an error on our part.

The first issue was that a newline `\n` was added into one of the `elements` `description` fields, which was causing the PNG to render incorrectly. Here's a minimal reproduction.

```
links:
  The FC4 Framework: https://fundingcircle.github.io/fc4-framework/
  Structurizr Express: https://structurizr.com/express
---
type: System Landscape
scope: Reproduce newline
description: Nothing

elements:
- type: Software System
  name: FooBar
  description: TODO \n BREAK
  tags: External
  position: '2000,2400'

size: A2_Landscape
```

**Comment by aviflax** [comment]
Thanks Dave, that’s great to hear, and thanks so much for the reproducer! Now I can add a test to the suite and catch this error — maybe even a whole new class of errors!

**Comment by aviflax** [comment]
I’ve added #224 to track the bug directly. Thanks again!

**Comment by ifyoumakeit** [comment]
Just to clarify it seems like it just expects nothing to be after `\n` in the description. I could see adding `\n` if you want complete control over line breaks. Not sure why that would be helpful in a generated diagram though.

**WORKS** 
```
- description: LINE 1\n
```
```
- description: |
     LINE 1\n
     LINE2
```
**BREAKS** (no inverse pun intended)
```
- description: LINE 1\nLINE 2
```
```
- description: |
     LINE 1\nLINE2
```

**Comment by aviflax** [comment]
Thanks Dave, that’s super helpful!

I think this is caused by fc4 not properly escaping (preserving?) escaped characters in the YAML source when passing the source over into the JavaScript page/window context of Structurizr Express.

If I’m right, that means that the line breaks end up being “actual” line breaks in the YAML, which can break the validity of the YAML. Your working examples don’t break the YAML: the first is just adding a blank line between properties of the map, which is valid in YAML; in the second the value of the property is a [block scalar](https://yaml-multiline.info) which is allowed to contain literal linebreaks, as long as indentation is preserved — which in this case, it is.

I’m not sure that makes sense… let me try to illustrate it like so:

### Working Examples

#### First

##### Escaped

```yaml
- description: LINE 1\n
  tags: External
```

##### Evaluated

```yaml
- description: LINE 1

  tags: External
```

#### Second

##### Escaped

```yaml
- description: |
     LINE 1\n
     LINE2
  tags: External
```

##### Evaluated

```yaml
- description: |
     LINE 1

     LINE2
  tags: External
```

### Breaking Examples

#### First

##### Escaped

```yaml
- description: LINE 1\nLINE 2
  tags: External
```

##### Evaluated

```yaml
- description: LINE 1
LINE 2
  tags: External
```

#### Second

##### Escaped

```yaml
- description: |
     LINE 1\nLINE2
  tags: External
```

##### Evaluated

```yaml
- description: |
     LINE 1
LINE2
  tags: External
```

I hope that makes it clear that in those latter cases, when the escaped chars are prematurely evaluated, the YAML becomes invalid, essentially because the documents are incorrectly indented. YAML indentation is notoriously tricky, but this is the first time I’ve seen someone have issues with it in the context of fc4. And, to be clear, I don’t think this is exactly like those cases, because the YAML you’ve authored _is_ valid; it’s just not being escaped properly in my code. I suppose this could be used as evidence of YAML being a brittle format, but I’d argue that string escaping/evaluating is fraught in general, whether or not YAML is involved.

Sorry for rambling, and thanks again for the great bug report!

**Comment by ifyoumakeit** [comment]
That was a great clarification of my clarification, thank you!
