### ISSUE TITLE
Proposal: redefine this project as a tool or toolset rather than a “framework”

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#226]
Today, FC4 is a:

> …framework that enables software creators and documentarians to author, publish, and maintain software architecture diagrams more effectively, efficiently, and collaboratively over time.

I’ve been calling it a _framework_ because for a good while I was just as focused on its methodology as its tooling. As I described in [the blog post introducing the project](https://engineering.fundingcircle.com/blog/2018/09/07/the-fc4-framework/), I asked my friend @ilangoodman if he could think of a singular term for a thing comprised of a tool and a methodology, he suggested “framework”. It made sense to me so I went with it.

Over time, however, I’ve noticed that the terms “framework” and “methodology“ are doing the project no favors. They seem to be vague and off-putting, and they seem to be dampening interest in the framework. On the other hand, when I’ve tried describing FC4 as a *tool* the response has been uniformly positive and eager. People seem to gravitate towards tools and be wary of more amorphous things such as frameworks.

I’ve come to believe that we should call FC4 a tool, and we should focus on, and emphasize, its tool-ness.

It can and will still have a methodology, but instead of being _the_ methodology, it would be _a_ methodology for using the tool — essentially a set of recommended practices, or guidelines, or something along those lines. This would all be part of the docs for the tool. ([The website](https://fundingcircle.github.io/fc4-framework/) would be reorganized accordingly.)

I’d love some feedback on this proposal. Anyone have any thoughts?

/cc @miketheman @ifyoumakeit @sldblog

**Comment by sldblog** [comment]
👍 I am in favour of using "tool" for the reasons you mentioned.

In the [Legal Aid Agency architecture diagrams][laa-diagrams], we use the phrase

> We use the [FC4 toolset][fc4-toolset] to normalise the source of C4 diagrams authored with [Structurizr Express][se].

[laa-diagrams]: https://github.com/ministryofjustice/laa-architectural-diagrams
[se]: https://structurizr.com/help/express
[fc4-toolset]: https://fundingcircle.github.io/fc4-framework/methodology/toolset.html

**Comment by aviflax** [comment]
Thanks Dávid!

**Comment by miketheman** [comment]
Thanks for writing this - it helps clarify the intent of this particular tool.

Is this repo also in scope for a rename? The directory layout of the repo is a little confusing to a newcomer - I naturally looked at the `bin/` directory first, but nothing in there is fc4-soecific, rather the "thing" that I want is in the `tool/` subdirectory.
Will the repo layout be modified as well?

**Comment by aviflax** [comment]
Thanks Mike, that’s great to hear!

> Is this repo also in scope for a rename? … Will the repo layout be modified as well?

Definitely. I neglected to mention this in the body of the issue, but yes, I’ve observed the same thing and I intend to reorg the repo as part of this. So we’ll end up with a single `bin` directory, one `docs`, one README, etc.
