### ISSUE TITLE
The Future of FC4

### ISSUE THREAD

**Issue by aviflax** [FundingCircle/fc4-framework#229]
## Today

Today, FC4 is:

> …a framework that enables software creators and documentarians to author, publish, and maintain software architecture diagrams more effectively, efficiently, and collaboratively over time.

So far it’s been fairly successful in achieving that purpose. Since its inception ~20 months ago we’ve created at least 24 substantial diagrams within Funding Circle, some of which we’ve updated and re-published numerous times; it’s also being used at the [UK Ministry of Justice][laa-architectural-diagrams-repo] and at [Warby Parker][warby-parker].

However:

* Numerous people have asked why the diagram data format couples the “content” and the “presentation” — it seems this aspect of FC4 is a “smell” for some people
* I’ve found that because each diagram definition is completely discrete and self-contained, any element that appears on multiple diagrams — which is many of them — is therefore defined repeatedly and duplicatively, leading to drift and inconsistencies, and/or increased maintenance overhead to keep the definitions in sync
* Similarly, because styles must be defined for each diagram, it’s difficult and/or costly to maintain a consistent visual style across a corpus of diagrams
* I’ve heard from 4–5 people across Funding Circle that their jobs would be much easier if we had a central-single-source-of-truth catalog for all of our systems
* [Simon Brown][simon-brown] (the creator of [C4][c4-model], [Structurizr][structurizr], and [Structurizr Express][structurizr-express]) has been persistent and consistent in his posts that while people may come for the diagrams, they stay for the models — i.e. the core value in C4 is *modeling* rather than *diagramming* ([example][simon-brown-example-tweet])
* The data format/DSL used by FC4, which was defined by Simon Brown using JSON conventions for use within Structurizr Express (SE), isn’t particularly expressive
  * It wouldn’t be hard to devise a more expressive data format/DSL (and in fact we’ve [already done so][ep01])

## A Proposed Future

Therefore, I propose that in the near future we redefine FC4 as:

> …a tool for cataloguing, modeling, and documenting software systems.

And:

* Finish implementing the changes defined in [EP01][ep01] that will decouple FC4 models and views with a new DSL
* Shift the central focus of FC4 from *views/diagrams* to a single, central, unified *model/catalog* of *all* relevant systems, people, and other elements
* Add a feature that would publish the *model/catalog* as a data-oriented website that would be both browseable by humans and queryable by machines via a Web API
  * This feature would leverage [Datasette][datasette] heavily; the only non-trivial implementation work would be to export the model/catalog to an SQLite database. Datasette would take it from there.

Here’s a [Container diagram][container-diagram] that depicts this possible future of FC4:

![fc4-future-02-container](https://user-images.githubusercontent.com/141844/68267938-35d10400-0022-11ea-9f0f-00343ff0e72d.png)

As you can see, this conception of FC4 places the model/catalog at the center of the system — it’s _the data_ that’s the most valuable element of the system.

## Getting There

Here’s some guesses about the scale of the work involved in implementing this future:

Change | Nature of the Work | Status | Scale in Person-Weeks
------ | ------------------ | ------ | -----
Finish implementing the new DSL as per EP01 | implementation in code | [In progress][issue-108] | ~2–3
Implement rendering of FC4 views | UX design, implementation in code | [Planned][project-1] | ~2–3
Shift the central focus | Mostly reorganizing and revising the docs | Good chunk of thinking has been done | ~1
Feature to publish the model/catalog as a Web site+API | Mostly exporting the data to SQLite | Not started | ~2–3

These guesses assume that I’m doing most of the work, mostly on my own.

## Open Questions

* Should FC4 retain the ability to work with SE diagram definitions?
  * Could be useful, and would certainly help with backwards-compatibility, but would also make FC4 more complex, harder to maintain, and harder to explain.
  * I’m inclined to keep supporting SE diagrams alongside the new DSL for ~6 months or so, and then remove it. The only support I’d be inclined to retain would be a feature to convert an SE diagram to the new DSL.
* Should FC4’s formatting feature support the new model DSL?
  * Since the files using the new DSL won’t be processed by SE, changes made to those files will be mostly intentional — in other words, we won’t be dealing with the “diff noise” that SE tends to introduce; eliminating this noise is the primary value of this feature — I think.
  * Also, the feature is lossy; [it erases comments][issue-9-preserve-comments]. This is pretty terrible, and non-trivial to fix.

## Feedback Please!

This is what I have in mind, but my ideas need to be challenged and honed by questions, concerns, suggestions, etc. Please share any thoughts you might have on any aspect of this proposal!

/cc @sldblog @miketheman 

[c4-model]: https://c4model.com
[container-diagram]: https://c4model.com/#coreDiagrams
[datasette]: https://datasette.readthedocs.io/en/stable/
[ep01]: https://github.com/FundingCircle/fc4-framework/blob/7984a94/proposals/ep01-decouple-models-and-views-new-dsl/ep01-decouple-models-and-views-new-dsl.md
[issue-9-preserve-comments]: https://github.com/FundingCircle/fc4-framework/issues/9
[issue-108]: https://github.com/FundingCircle/fc4-framework/issues/108
[laa-architectural-diagrams-repo]: https://github.com/ministryofjustice/laa-architectural-diagrams
[project-1]: https://github.com/FundingCircle/fc4-framework/projects/1
[simon-brown]: https://simonbrown.je
[simon-brown-example-tweet]: https://twitter.com/simonbrown/status/1191285136110817286
[structurizr]: https://structurizr.com/
[structurizr-express]: https://structurizr.com/express
[warby-parker]: https://www.warbyparker.com

**Comment by miketheman** [comment]
This in a good write up, and definitely the concept of a single source and multiple renders is a good one - one that I think is done in the [c4builder package](https://www.npmjs.com/package/c4builder) by virtue of using naming and directory hierarchy structure to convey the different levels. I don't know if that's better, but it definitely conveys a place to store information and link to it - I guess Datasette will offer some of that as well.
That project uses the same styles, and doesn't need SE (as far as I can tell).

I definitely like the idea of a flexible system container/component catalog - we had previously discussed that in person - and thinking about the different ways I'd want to express diagrams and relationships differs by which audience I'm talking to - as well as how many components are involved in an interaction.
Example:
- a central banking system might have tens of connections to other systems, but if all I want to discuss is the bank-to-bank interaction system, I should be able to tag and diagram those part of that interaction.

This might be digressing from the structure, but I think that if the tool starts to split the visual rendering concerns from the data modeling concerns, these ideas can be fleshed out further.

**Comment by simonbrowndotje** [comment]
The reasons you outline are why I don't recommend using Structurizr Express for anything more than the odd diagram. As I've mentioned before, I'd recommend looking at the full Structurizr toolset, which is very different from Express in that it's model based ... so you can generate multiple views from a single model of elements and the relationships between them. Features I'm looking at adding next year include the ability to share content between workspaces (e.g. element/relationship definitions and diagrams styles).

If you don't want to look at the Structurizr cloud/on-premises service, you still might get some benefit from the open source libraries (currently Java/.NET/TypeScript/PHP), which again allow you to generate multiple views (e.g. PlantUML diagrams) from a single model.

**Comment by aviflax** [comment]
@miketheman thanks for the feedback — that all makes sense!

> This might be digressing from the structure, but I think that if the tool starts to split the visual rendering concerns from the data modeling concerns, these ideas can be fleshed out further.

Agreed. Thank you!

----

@simonbrowndotje thanks for the feedback!

> The reasons you outline are why I don't recommend using Structurizr Express for anything more than the odd diagram.

Yup, and that makes sense to me. The reason I started with Express, and that I’ve stuck with it so far, is that it defines and exposes a data model+format for diagrams. Defining diagrams _as data_ is so important to me that I just gave [a talk about it](https://twitter.com/flaximus/status/1199021633681395712) last week. And it’s extremely important to me to adhere to the [Docs as Code](https://www.writethedocs.org/guide/docs-as-code/) philosophy; FC4’s core purpose to date has been to enable collaborating on diagrams as data in text files in git repos.

> As I've mentioned before, I'd recommend looking at the full Structurizr toolset, which is very different from Express in that it's model based ... so you can generate multiple views from a single model of elements and the relationships between them.

Thank you! I definitely understand that distinction between Structurizr and Express, and your persistent, and consistent, evangelism for modeling over diagramming has been a massive influence on me and on my plans for the future of FC4.

I think Structurizr is a phenomenal tool and I tell people about it regularly. I just don’t think it’s a good fit for me or my org _right now_ because docs as code workflows involving _data_ in text files in git repos is crucial to us.

That said, I think it’s obvious in this proposal that my vision is for FC4 to follow in the footsteps of Structurizr in adopting, facilitating, and encouraging modeling. And I see opportunities to bring them closer together in the future. For example, I’m hoping to implement a feature to export an FC4 corpus into a Structurizr workspace. In other words, I’m super intersted in using Structurizr as a publication target, and as a place for people in my org to browse, view, and explore views and models.

> Features I'm looking at adding next year include the ability to share content between workspaces (e.g. element/relationship definitions and diagrams styles).

Excellent!

> …you still might get some benefit from the open source libraries (currently Java/.NET/TypeScript/PHP), which again allow you to generate multiple views (e.g. PlantUML diagrams) from a single model.

Great point, I’ll definitely take a look. Thank you!

**Comment by aviflax** [comment]
Related: I recently delivered a talk at [Clojure/conj 2019](https://2019.clojure-conj.org/): [_(Architecture) Diagrams as Data_](https://2019.clojure-conj.org/speaker-avi-flax/) and [the video](https://youtu.be/HmHOYkTVxIg) and [the slides](https://github.com/aviflax/presentations/tree/master/diagrams-as-data) have been posted.

**Comment by aviflax** [comment]
I’ve had mostly positive feedback to this proposal, and it seems like discussion has died down (here and in other fora) so I’m closing this. However: follow-up questions, comments, concerns, suggestions, etc are all welcome.
