### ISSUE TITLE
FC4 roadmap question

### ISSUE THREAD

**Issue by kpmg-jp-jnorton** [FundingCircle/fc4-framework#234]
I’m intrigued by the last portion of your [clojure/conj 2019 talk](https://www.youtube.com/watch?v=HmHOYkTVxIg&list=PLZdCLR02grLqSy15ALLAZDU6LGpAJDrAQ&index=14) when you explain how you are pivoting to a catalog (or model) of the system.
 
Can you provide some insights on how one could replace YAML with actual clojure syntax for the architecture diagrams?
 
If so, do you think you could express the DSL of this language as clojure.spec?

**Comment by aviflax** [comment]
> Can you provide some insights on how one could replace YAML with actual clojure syntax for the architecture diagrams?

While Clojure has been extremely influential and instrumental in designing and building FC4, and in developing my vision for its future (as described in my talk and in #229), I want the tool to be usable by almost any software [documentarian](https://www.writethedocs.org/documentarians/), including those who’ve never even heard of Clojure — which is probably most of them!

Therefore, I don’t have any plans to replace YAML with Clojure S-expressions nor [EDN](https://github.com/edn-format/edn), nor to add any support for EDN at all.

That said, I wouldn’t be opposed to _adding_ EDN as a new _alternative_ on-disk data format.

Alternatively, you might be able to maintain your diagram source files as EDN and convert them to YAML before passing the YAML to `fc4` for rendering. (This might be a good reason to add support to FC4 for reading diagram definitions from stdin. However, it wouldn’t be hard to write a script that would convert EDN files to YAML (leaving the EDN files alone), then invoke `fc4` to render the diagrams, then delete the YAML files.)

> If so, do you think you could express the DSL of this language as clojure.spec?

The code already includes specs for Structurizr Express diagram definitions, and I’ve been working on specs for the new FC4 DSLs for models and views. Are you interested in using fc4 as a library, so you can use its specs in your own code?

**Comment by aviflax** [comment]
Closing for now, but feel free to re-open if you’d like to continue the discussion.
