### ISSUE TITLE
Compilation error: 'fc4.integrations.structurizr.express.chromium-renderer' not found

### ISSUE THREAD

**Issue by mathpunk** [FundingCircle/fc4-framework#236]
I'm attempting to get up and running on an Arch Linux system, and I cannot get past this error. I've tried loading this namespace in the repl, and I've tried running tests. I'm getting more or less the same error but not more information (that I understand) about how to continue.

**Comment by mathpunk** [comment]
Note: I have chromium at version 78 and google-chrome-stable at 77. That could cause problems but I don't know if it's causing this problem.

**Comment by aviflax** [comment]
Hi @mathpunk thanks so much for the bug report! I really appreciate it. I’ve never used Arch before, but now that I have an Arch user wanting to use FC4, I’d be delighted to try to add it to the set of test environments. I’ll look into this and report back within a day or two. Thanks again!

**Comment by aviflax** [comment]
Ah, I just re-read your bug report and it registered that you’ve already tried to do some debugging, so obviously you’re familiar with Clojure to some degree. I just want to check: is your goal to simply _use_ FC4, or are you also interested in working _on_ FC4?

Thanks!

**Comment by mathpunk** [comment]
Ooh, well I am mostly interested in using it, but the reason I got excited to use it is because there is some great work happening in the mathematics of diagram languages so, maybe in the future I could contribute.

**Comment by aviflax** [comment]
Very cool! I’m intrigued by the work you mentioned; if you have a chance please do share some links!

(So far I’ve stubbornly avoided employing any sort of mathematics or graph theory into FC4 but that’s just due to my own biases and imposter syndrome, etc. It’s been clear to me for awhile that the brute-force relationship traversal in the code right now will need to be replaced with graph traversal algorithms over graph data structures, e.g. using [Loom](https://github.com/aysylu/loom) or something similar.)

**Comment by mathpunk** [comment]
Hmmmm. I checked out `bug-236`. When I ran `clj -A:dev:test` and then 

```
(do
     (require '[eftest.runner :refer [find-tests run-tests]])
     (run-tests (find-tests "test") {:fail-fast? true}))
```
I got

```
Syntax error (FileNotFoundException) compiling at (fc4/integrations/structurizr/express/chromium_renderer.clj:1:1).
Could not locate clj_chrome_devtools/automation__init.class, clj_chrome_devtools/automation.clj or clj_chrome_devtools/automation.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
``` 
again. I looked at the changes you made, and now I see how there's a collection of launch paths. Included is `"/usr/bin/chromium" ; Debian`. That is the value of `which chromium` in my shell so, I don't think this is the root cause.

**Comment by aviflax** [comment]
@mathpunk what JVM/JRE are you using, what version of Clojure, and what version of the `clojure` script?

(You can check the version of `clojure` like so: `head -n 3 $(which clojure)`)

Also, have you tried running fc4 via a distribution artifact, i.e. one of the .tar.gz files attached to one of the [releases](https://github.com/FundingCircle/fc4-framework/releases)?

**Comment by mathpunk** [comment]
openjdk version "11.0.5" 2019-10-15
clojure version 1.10.1.447

I'm not quite sure how to run via distribution artifact, actually, and was going to suggest some documentation clarification. The `bin` directory has linting scripts, the `tool/dist/fc4` executable says `Error: Unable to access jarfile ./dist/fc4.jar`. On a guess I did  `./bin/pkg-uberjar` and got

```
Cleaning target
Creating target/classes
  Compiling fc4.files
  Compiling fc4.image-utils
  Compiling fc4.integrations.structurizr.express.chromium-renderer
Execution error (FileNotFoundException) at fc4.integrations.structurizr.express.chromium-renderer/loading (chromium_renderer.clj:1).
Could not locate clj_chrome_devtools/automation__init.class, clj_chrome_devtools/automation.clj or clj_chrome_devtools/automation.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```

**Comment by mathpunk** [comment]
While flailing around I also tried wrapping that `"/usr/bin/chromium" ` string in a `(file ...)` but no change.

**Comment by aviflax** [comment]
> I'm not quite sure how to run via distribution artifact, actually, and was going to suggest some documentation clarification.

Good feedback — thanks!

Manual installation instructions are [here](https://fundingcircle.github.io/fc4-framework/tool/#manually) — but I’m sure they’re far from perfect. And of course, not very findable — we need a _Getting Started_ guide. I’m open to any feedback/suggestions/contributions you’d like to share!

> The `bin` directory has linting scripts…

Yeah, the tool isn’t really meant to be run from source right now. It’s possible, but not currently documented. (`clojure -A:main [options] [path]`)

> …the `tool/dist/fc4` executable says `Error: Unable to access jarfile ./dist/fc4.jar`

Yeah, that script isn’t meant to be run from within the repo; it’s bundled up along with the überjar into each distribution artifact.

As for the compilation errors, it appears that a dependency is missing. I’m going to try to reproduce using the version info you provided.

In the meantime, I’d really like to see whether you can use the distribution artifact attached to [this prerelease](https://github.com/FundingCircle/fc4-framework/releases/tag/prerelease_bug-236). Maybe you could give it a try and report back?

**Comment by mathpunk** [comment]
When you say "use the distribution artifact", can you tell me exactly what you mean? When I download the first tar.gz in the list, and open it, it looks exactly like the source directory I cloned, except has no git history. The file in the `dist` directory gives me the same "no jar" error.

**Comment by aviflax** [comment]
> I looked at the changes you made, and now I see how there's a collection of launch paths. Included is `"/usr/bin/chromium" ; Debian`. That is the value of `which chromium` in my shell so, I don't think this is the root cause.

BTW, this is surprising to me. I’ve been experimenting with an Arch install in a Docker container, and after I run `pacman -S chromium` if I then run `which chromium` I get `/usr/sbin/chromium` — perhaps we’re using different versions of Arch? I’m using the Docker image [archlinux:20191105](https://hub.docker.com/layers/archlinux/library/archlinux/20191105/images/sha256-1097437745db73ba839d60b9b9b96e6648e62751519a1319bfccc849f6a3f74c)

**Comment by mathpunk** [comment]
Unless I downloaded it to the wrong place, which is entirely possible, hang on hang on...

**Comment by mathpunk** [comment]
Ugh sorry for the brainographical error. The artifact starts up fine and watches for YAML files.

**Comment by aviflax** [comment]
Let’s look at a release that has a much shorter description, such as [the latest release](https://github.com/FundingCircle/fc4-framework/releases/tag/release_2019.12.05-d9bb848) — here’s a screenshot of that page:

<img width="1392" alt="Screen Shot 2019-12-05 at 5 18 27 PM" src="https://user-images.githubusercontent.com/141844/70278944-49879b80-1783-11ea-8b37-8bc343138503.png">

In that list of assets at the bottom, the first asset/file in the list has a name starting with `fc4-tool` and ending with `.tar.gz`. That’s a distribution artifact, i.e. a release artifact. If you download that and expand it, you’ll see that it contains a directory with three files.

**Comment by aviflax** [comment]
lol, no worries, that’s great!

Can you confirm that the tool can render a diagram successfully? (If you need a diagram definition you can use [this one](https://github.com/FundingCircle/fc4-framework/blob/release_2019.12.05-d9bb848/docs/tool/fc4-tool-02-container.yaml).)

**Comment by aviflax** [comment]
There’s still the question of why you’re having trouble compiling from source and running the tests, but that seems less urgent to me than being able to just _use_ the tool.

**Comment by aviflax** [comment]
BTW, given this experience I’m definitely keen on getting some suggestions on improving the manual installation instructions…

**Comment by mathpunk** [comment]
Yeah I kept downloading the source like a n00b. As for the version, I really should have made it clear that I'm running Manjaro, which is supposedly a thin wrapper around Arch but I see that `uname -a` gets me 

`Linux manifold 4.19.81-1-MANJARO #1 SMP PREEMPT Tue Oct 29 12:49:04 UTC 2019 x86_64 GNU/Linux` which appears to be wildly behind where Arch itself is and is causing me to rethink my choices in life.

Working on rendering a document now....

**Comment by aviflax** [comment]
<img src="https://i.kym-cdn.com/entries/icons/mobile/000/009/993/tumblr_m0wb2xz9Yh1r08e3p.jpg">

**Comment by mathpunk** [comment]
It wooooooorks! Updates the picture I opened in emacs and everything. Rock! 

Now to.... ... understand the C4 model! Thanks for your help! And I haven't forgotten that I owe you links on graphical languages in math. Maybe this one? https://youtu.be/r_giN0VU7qo  I haven't seen this particular lecture but, Prof. Baez's general style is to unpack the reasons why he has developed his research program, point out how diagrams have been used in sciences historically, then teach about the math that is useful for understanding those diagrams. You should watch this until you get the gist and then quit when you get bored, because it will probably get pretty algebraic up in there.

**Comment by aviflax** [comment]
Great, my pleasure!

I’ll check out that talk — thanks!
