### ISSUE TITLE
Structurizr Express is being discontinued

### ISSUE THREAD

**Issue by simonbrowndotje** [FundingCircle/fc4-framework#268]
Hi folks, for a number of reasons, we've made the decision to discontinue Structurizr Express, and it will be unavailable from 1st July 2020. The workspace version of Structurizr (free and paid plans, cloud service and on-premises installation) remains as-is.

I can see from commentary on the proposals (e.g. [EP01](https://github.com/FundingCircle/fc4-framework/blob/7984a94/proposals/ep01-decouple-models-and-views-new-dsl/ep01-decouple-models-and-views-new-dsl.md)) and issues (e.g. #229) that you're considering how to render diagrams specified with the new DSL, and that your new workflow will be much more about forward generating diagrams from your DSL, rather than round-tripping Express definitions. If you're not going to build your own rendering engine, you can still use Structurizr for rendering diagrams with a slightly modified workflow:

 1. Create and upload a Structurizr workspace JSON file via the [Structurizr web API](https://structurizr.com/help/web-api) ... the simplest way to do this is via one of the [Java/.NET/PHP/TypeScript client libraries](https://structurizr.com/help/client-libraries). The [Workspace export and import page](https://structurizr.com/help/workspace-export-and-import) shows a code example.
 2. Open the diagram editor as an _authenticated user_ to edit the diagram layout. Via the [scripting support](https://structurizr.com/help/scripting-diagrams) I've added a way to register a JavaScript callback (the ```onWorkspaceSaved(callback)``` function) that will allow you to write some code that will be executed when the workspace is saved. Using this in conjunction with Puppeteer, it's straightforward to open the diagram editor interactively, and export the PNG/SVG diagrams whenever the workspace is saved. [Here is a working example script](https://github.com/structurizr/puppeteer/blob/master/edit-and-export-private-diagrams.js).
 3. After modifying the layout of the diagram(s) contained in the workspace, the paper size and element x,y coordinates can be obtained by downloading the workspace JSON definition via the web API.
 
If you have privacy concerns with uploading information to the cloud service, you can install the free version of the on-premises installation, which works in the same way. You may see an overall performance improvement too by having a local installation.

The key difference between the Express JSON definition and the workspace JSON definition is that the latter separates the model (elements and relationships) from the (zero or more) views defined in the workspace. In addition, I've [open sourced some tooling](https://github.com/structurizr/express-to-workspace) that will convert a Structurizr Express JSON/YAML diagram definition to a Structurizr workspace JSON definition. This will allow you to preserve any diagrams currently stored as Express definitions, until they are migrated to the new DSL.

Apologies for the inconvenience caused. If you have any questions or need any assistance, do please let me know.

**Comment by aviflax** [comment]
Hi Simon, thank you so much for your message! No apologies are needed. I very much appreciate you notifying us about this with plenty of notice and with so much generous and helpful information.

I’ve been planning on implementing my own renderer for awhile, mostly so it’d work offline and wouldn’t require child processes and inter-process communication (IPC). This news simply raises the priority of that work.

Thank you!

**Comment by simonbrowndotje** [comment]
No problem, you're welcome!

I see that you're looking at dali to create SVG ... if you only need to do one-way rendering (rather than providing a UI for users to drag boxes around and modify diagram layout), the [C4-PlantUML](https://github.com/RicardoNiepel/C4-PlantUML) project is worth a look, as the notation is better than default PlantUML, and the graphviz automatic layout engine does a decent job most of the time. That does run in a separate process though, but it will save you building a rendering engine.

I'm definitely interested to see how you get on with the new DSL; I can see it being useful for people who want to create a model with human-readable text (rather than code or a UI). I spent 90 minutes putting a quick prototype together, which parses the FC4 YAML model into a Structurizr workspace, and generates some diagrams automatically.

- [YAML model](https://github.com/structurizr/java-extensions/tree/master/structurizr-examples/src/com/structurizr/example/fc4/bigbankplc/model)
- [main](https://github.com/structurizr/java-extensions/blob/master/structurizr-examples/src/com/structurizr/example/FC4.java)
- [Fc4Importer](https://github.com/structurizr/java-extensions/blob/master/structurizr-fc4/src/com/structurizr/io/fc4/Fc4Importer.java) (this has limited support for systems and users, and creates a number of views automatically)
- [Structurizr workspace](https://structurizr.com/share/50080)

Some example diagrams are as follows:

![structurizr-50080-SystemLandscape](https://user-images.githubusercontent.com/1009874/72337762-02ae8f00-36bb-11ea-9cf0-2a7525fb887f.png)
![jP9TInjT4CVlyodcyRbG8IQfMeL2GPDAAPXMZBQNCZaxcnnoNhPdpff8wNVld4rsJUpItbI5HUVbT_xpdxdWY26MrXpexFtaYIFPQtGPAopeiFEVTigK6PN1m3p6Wj_r-m6NlPcEyt9QCWNbNIGNUyhR_grM63B_MLD1fZywFRenwEBz-BflKS11Ghr2dlhts8THgb_5ryIZTXHUxm5RU4TkCm4hD0GMLt0y60nMwTE9Eafi](https://user-images.githubusercontent.com/1009874/72337809-1954e600-36bb-11ea-95c1-a127eaa0478d.png)

As I said, if you need anything, do let me know.

**Comment by simonbrowndotje** [comment]
I just stumbled across [arch-as-code](https://github.com/nahknarmi/arch-as-code) - it looks like they are taking a similar approach to you, using a YAML-based model as the source. The schema is relatively similar to your DSL too - [example](https://github.com/nahknarmi/arch-as-code/blob/master/documentation/products/arch-as-code/data-structure.yml).

**Comment by aviflax** [comment]
@simonbrowndotje 🤯🤯🤯 wow. I’ll check it out! Thanks again for all the help! 🤗

**Comment by arichiardi** [comment]
Hello folks!

We are investigating a tool for working with the c4 model and at this point we were thinking of `fc4`. However this issue changed my mind a bit and now...would you suggest checking `arch-as-code` instead? Do you see the two tools converging into one?

**Comment by aviflax** [comment]
Hi Andrea! Your concern is totally understandable.

I can’t make any promises, but I’m determined to ensure that FC4 survives the death of Structurizr Express. I haven’t yet properly documented my plan to do so, but in a nutshell it involves (a) designing and implementing a new C4 YAML DSL that decouples models and views, as per [Enhancement Proposal EP01: Decoupling Models and Views with a New DSL](https://github.com/FundingCircle/fc4-framework/blob/b3b7203/docs/archive/proposals/ep01-decouple-models-and-views-new-dsl/ep01-decouple-models-and-views-new-dsl.md); and (b) implementing a new renderer as per #5.

I’ve documented this plan in more detail in #284. If you have any questions, suggestions, concerns, or any feedback at all, I’d love to hear it! (Ideally over in #284 tho.)

As for arch-as-code — I’ve looked at that project a few times, to try to evaluate it, and every time I look at it I have a gut reaction that its goals and its underlying philosophy don’t quite jive with my vision for FC4. For example, their DSL makes sense, but it’s not very user-friendly. I want to make architecture modeling and diagramming simple, easy, accessible, useful, effective, and enjoyable for a broad swath of people who are involved in the creation of software systems — product managers, tech writers, documentarians of any background — way beyond programmers. Sorry for the rant… I just have a gut feel that either our goals or our tastes may be too divergent for these two projects to merge. That said, I shouldn’t just proceed with the assumption that my gut is correct. I’m going to get in touch with the creators of arch-as-code and discuss this all with them. Thanks for the prodding!

**Comment by arichiardi** [comment]
Hey @aviflax Thanks for the thorough response.

I definitely share your goals, in the way that I strongly believe (slightly tangential) that if you go for yaml you are implicitly saying you want to target humans rather than machines (otherwise you would have picked Json 😁).

I will follow the issues there.

**Comment by simonbrowndotje** [comment]
Just to add ... the on-premises version of Structurizr (free and paid) includes Structurizr Express. If you download this now, you'll be able to use the current version of fc4 against your local installation. There will be no updates after June 30th though, but it's certainly a short-term option that you can start with immediately. It's also worth asking @aviflax if the fc4 project will provide a way to convert current fc4 definitions to the new version, once EP01 is implemented.

In addition to thinking about the input format (e.g. YAML), it's also worth thinking about what output you are looking for, in terms of diagram look and feel, and layout. arch-as-code uses the full version of Structurizr, so you'll get good looking diagrams with keys/legends, but it's designed to use the auto-layout feature, which means you have very little control over how elements are organised. If manual diagram layout is important to you, you may want to skip arch-as-code. Again, it's worth asking @aviflax how the fc4 renderer will work in this respect.

**Comment by aviflax** [comment]
> Just to add ... the on-premises version of Structurizr (free and paid) includes Structurizr Express. If you download this now, you'll be able to use the current version of fc4 against your local installation. There will be no updates after June 30th though, but it's certainly a short-term option that you can start with immediately.

Thanks Simon, that’s super helpful and makes a ton of sense!

> It's also worth asking @aviflax if the fc4 project will provide a way to convert current fc4 definitions to the new version, once EP01 is implemented.

I’ve been wondering this myself :trollface: 

In all seriousness, I think the answer is, “if there’s demand, then sure.” FC4 doesn’t have many users, so I’ve had in mind that when I go to convert my corpus of Structurizr Express diagrams into an FC4 corpus (1 model + N views) I’ll probably hack together some sketchy script to do the conversion, and if I do then I may as well offer it up to others to try out.

> In addition to thinking about the input format (e.g. YAML), it's also worth thinking about what output you are looking for, in terms of diagram look and feel, and layout.

+1

> arch-as-code uses the full version of Structurizr, so you'll get good looking diagrams with keys/legends, but it's designed to use the auto-layout feature, which means you have very little control over how elements are organised. If manual diagram layout is important to you, you may want to skip arch-as-code.

Good to know!

> Again, it's worth asking @aviflax how the fc4 renderer will work in this respect.

I’m open to feedback on this, but as of now I’m planning to support only manual layout, as per this slightly out-of-date [example in the EP01 proposal](https://github.com/FundingCircle/fc4-framework/blob/master/docs/archive/proposals/ep01-decouple-models-and-views-new-dsl/ep01-decouple-models-and-views-new-dsl.md#views). This is 80% because I think it’s better, and maybe ~20% because of the effort that would be required to implement auto layout — in short, I don’t think it’d be worthwhile — but that should be discussed in a different ticket, e.g. #5.

**Comment by aviflax** [comment]
> Just to add ... the on-premises version of Structurizr (free and paid) includes Structurizr Express. If you download this now, you'll be able to use the current version of fc4 against your local installation.

I forgot to mention: this makes a ton of sense, and FC4 is _almost_ ready to support this — I’d just need to add a CLI option to specify an alternate URL for Structurizr Express. If anyone reading this would use such an option, please comment on #288.

**Comment by aviflax** [comment]
@simonbrowndotje I hope you’re well. Any chance you’d consider pushing out the retirement of Structurizr Express just a bit, due to the pandemic? The situation has delayed my ability to remove this tool’s dependency on it. Either way, thank you, and take care!

**Comment by simonbrowndotje** [comment]
Yes, thanks, hope you are too. Our plan is to remove Express from the cloud service as scheduled, but we're going to leave it in the [on-premises installation](https://structurizr.com/help/on-premises) for a couple of months after that.

**Comment by aviflax** [comment]
Thanks @simonbrowndotje — I can work with that!
